name: TSMenuPlugin
version: '${project.version}'
main: com.christmas.tsmenuplugin.TSMenuPlugin
api-version: 1.17
authors: [ christmas, ChR1stMas ]
description: A Menu Plugin for TheServer.wtf
commands:
  getmenu:
    description: creates menu and gives player menu item
  openmenu:
    description: opens a specified menu overview
  editpage:
    description: allows you to edit a page and stuff
  getmenubook:
    description: gives the player a book from a menu
  delpage:
    description: deletes a page of a menu. specify menu before
permissions:
  utility.modeler.*:
    children:
      utility.modeler.getmenu: true
      utility.modeler.delpage: true
      utility.modeler.editpage: true
      utility.modeler.openmenus: true
      utility.modeler.menu: true
